---
title: "Rosies Plots"
author: "Rosie"
date: "2024-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(tidyverse)
library(rvest)
library(xml2)

```
# Water Year Index

I'm going to try and graph the water year indices by pulling them from online. Wish me luck.
https://cdec.water.ca.gov/reportapp/javareports?name=WSIHIST 

```{r}

#URL of historical water year index
url <-  "https://cdec.water.ca.gov/reportapp/javareports?name=WSIHIST"

#extract the block of text with the table of water year indices
test = read_html(url) %>%
  html_nodes("section") %>%
  html_elements("pre") %>%
  html_text()

#break the block of text up by rows
Test3 = str_split(test, "\n")[[1]]

#break the rows out into columns based on their position. THere's probalby a better way.
WYindex = data.frame(WYs = Test3[16:137]) %>%
  mutate(Year = as.numeric(str_sub(WYs, 1,4)),
         SacOctMar = as.numeric(str_trim(str_sub(WYs, 8,12))),
         SacAPRJul = as.numeric(str_trim(str_sub(WYs, 16,20))),
         SacWYsum = as.numeric(str_trim(str_sub(WYs, 24, 28))),
         SacIndex = as.numeric(str_trim(str_sub(WYs, 32, 36))),
         SacYr_Type = str_trim(str_sub(WYs, 41, 42)),
                  SJOctMar = as.numeric(str_trim(str_sub(WYs, 47, 52))),
         SJAPRJul = as.numeric(str_trim(str_sub(WYs, 55,60))),
         SJWYsum = as.numeric(str_trim(str_sub(WYs, 63, 68))),
         SJIndex = as.numeric(str_trim(str_sub(WYs, 71, 76))),
         SJYr_Type = str_trim(str_sub(WYs, 79, 81))) %>%
  select(-WYs) %>% #get rid of origional text
  
  #turn water year type into a factor to make it graph better
  mutate(SacYr_Type = factor(SacYr_Type, levels = c("C", "D", "BN", "AN", "W")))

#plot water year index by year, color-coding by water year type. 
ggplot(WYindex, aes(x = Year, y = SacIndex, fill = SacYr_Type)) + geom_col()+
  scale_fill_manual(values = c("firebrick", "orange", "yellow","skyblue", "blue"), name = "Water Year Type")+
  ylab("Sacramento Valley Index")+ theme_bw()

```

